### ISSUE TITLE
Plugin crashing Homebridge

### ISSUE THREAD

**Issue by pbksol** [toto/homebridge-airrohr#11]
Sometimes the Plugin crashes on callback which will cause Homebridge to crash.

`/usr/local/lib/node_modules/homebridge-airrohr/index.js:187
        callback(null);
        ^
TypeError: callback is not a function
    at AirRohrAccessory.updateCache (/usr/local/lib/node_modules/homebridge-airrohr/index.js:187:9)
    at Timeout.AirRohrAccessory.setInterval [as _onTimeout] (/usr/local/lib/node_modules/homebridge-airrohr/index.js:213:12)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
`

Local URL, sometimes not responding due to bad WiFi connectivity of the esp.

**Comment by pbksol** [comment]
Haha… Looked at the Code… You made a change 22 Minutes ago… I think we can close it
