### ISSUE TITLE
Warnings during homebridge startup: characteristic was supplied illegal value: undefined!

### ISSUE THREAD

**Issue by roboterm** [toto/homebridge-airrohr#42]
[21/12/2020, 13:05:31] Received warning for the plugin 'homebridge-airrohr' from the characteristic 'Current Temperature': characteristic was supplied illegal value: undefined! This might throw errors in the future!
[Current Temperature@Homebridge CAD8] characteristic was supplied illegal value: undefined! This might throw errors in the future!
[21/12/2020, 13:05:31] Received warning for the plugin 'homebridge-airrohr' from the characteristic 'Current Relative Humidity': characteristic was supplied illegal value: undefined! This might throw errors in the future!
[Current Relative Humidity@Homebridge CAD8] characteristic was supplied illegal value: undefined! This might throw errors in the future!
[21/12/2020, 13:05:31] Received warning for the plugin 'homebridge-airrohr' from the characteristic 'Air Quality': characteristic was supplied illegal value: undefined! This might throw errors in the future!
[Air Quality@Homebridge CAD8] characteristic was supplied illegal value: undefined! This might throw errors in the future!
[21/12/2020, 13:05:31] Received warning for the plugin 'homebridge-airrohr' from the characteristic 'PM2.5 Density': characteristic was supplied illegal value: undefined! This might throw errors in the future!
[PM2.5 Density@Homebridge CAD8] characteristic was supplied illegal value: undefined! This might throw errors in the future!
[21/12/2020, 13:05:31] Received warning for the plugin 'homebridge-airrohr' from the characteristic 'PM10 Density': characteristic was supplied illegal value: undefined! This might throw errors in the future!
[PM10 Density@Homebridge CAD8] characteristic was supplied illegal value: undefined! This might throw errors in the future!

**Comment by gielk** [comment]
[03/03/2021, 15:26:59] [homebridge-airrohr] This plugin generated a warning from the characteristic 'Air Quality': characteristic value expected number and received undefined. See https://git.io/JtMGR for more info.
[03/03/2021, 15:26:59] [homebridge-airrohr] Error: 
    at AirQuality.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2164:105)
    at AirQuality.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1996:16)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1517:24
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at AirQuality.<anonymous> (/usr/local/lib/node_modules/homebridge-airrohr/index.js:185:32)
    at AirQuality.emit (events.js:315:20)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1493:14
    at new Promise (<anonymous>)
    at AirQuality.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1491:12)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:113:16)
    at AirQuality.Characteristic.handleGetRequest (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:648:24)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1507:27)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:113:16)
    at Bridge.Accessory.handleCharacteristicRead (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Accessory.js:1273:24)
[03/03/2021, 15:26:59] [homebridge-airrohr] This plugin generated a warning from the characteristic 'PM2.5 Density': characteristic value expected float and received undefined. See https://git.io/JtMGR for more info.
[03/03/2021, 15:26:59] [homebridge-airrohr] Error: 
    at PM2_5Density.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2164:105)
    at PM2_5Density.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1970:16)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1517:24
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at PM2_5Density.<anonymous> (/usr/local/lib/node_modules/homebridge-airrohr/index.js:188:32)
    at PM2_5Density.emit (events.js:315:20)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1493:14
    at new Promise (<anonymous>)
    at PM2_5Density.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1491:12)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:113:16)
    at PM2_5Density.Characteristic.handleGetRequest (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:648:24)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1507:27)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:113:16)
    at Bridge.Accessory.handleCharacteristicRead (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Accessory.js:1273:24)
[03/03/2021, 15:26:59] [homebridge-airrohr] This plugin generated a warning from the characteristic 'PM10 Density': characteristic value expected float and received undefined. See https://git.io/JtMGR for more info.
[03/03/2021, 15:26:59] [homebridge-airrohr] Error: 
    at PM10Density.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2164:105)
    at PM10Density.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1970:16)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1517:24
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at PM10Density.<anonymous> (/usr/local/lib/node_modules/homebridge-airrohr/index.js:191:32)
    at PM10Density.emit (events.js:315:20)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1493:14
    at new Promise (<anonymous>)
    at PM10Density.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1491:12)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:113:16)
    at PM10Density.Characteristic.handleGetRequest (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:648:24)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1507:27)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:113:16)
    at Bridge.Accessory.handleCharacteristicRead (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Accessory.js:1273:24)
